-- MySQL Script generated by MySQL Workbench
-- Fre 02 Dez 2016 12:38:14 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kingdom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kingdom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kingdom` DEFAULT CHARACTER SET utf8 ;
USE `kingdom` ;

-- -----------------------------------------------------
-- Table `kingdom`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kingdom`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `salt` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kingdom`.`questions_sets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kingdom`.`questions_sets` (
  `id` INT NOT NULL,
  `answer_one` VARCHAR(255) NOT NULL,
  `answer_two` VARCHAR(255) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_sets_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_questions_sets_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `kingdom`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kingdom`.`users_answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kingdom`.`users_answers` (
  `questions_sets_id` INT NOT NULL,
  `answer` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`questions_sets_id`, `answer`, `user_id`),
  INDEX `fk_questions_sets_has_users_users1_idx` (`user_id` ASC),
  INDEX `fk_questions_sets_has_users_questions_sets_idx` (`questions_sets_id` ASC, `answer` ASC),
  CONSTRAINT `fk_questions_sets_has_users_questions_sets`
    FOREIGN KEY (`questions_sets_id`)
    REFERENCES `kingdom`.`questions_sets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_questions_sets_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `kingdom`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
