site:
  build: .
  ports:
    - "80:80"
  volumes:
    - /home/user/eric/Projects/Webrobot:/var/www/html/
mysql:
  image: mysql:5.6.26
  environment:
   - MYSQL_ROOT_PASSWORD=root
   - MYSQL_DATABASE=root
  ports:
    - "3306:3306"